version: '3'
services:
  vue-webserver:
    build: ./docker/webserver7/
    volumes:
      - ./:/var/www:cached
      - ./docker/webserver7/config/php.ini:/usr/local/etc/php/php.ini
    working_dir: /var/www/
    ports:
      - 80:80
    container_name: vue-webserver