version: '3'
services:
  vue-webserver:
    image: davidt22/apache-php7.1-symfony3
    volumes:
      - ./:/var/www/web:cached
      - ./docker/webserver7/config/php.ini:/usr/local/etc/php/php.ini
      - ./docker/webserver7/config/project.conf:/etc/apache2/sites-enabled/
    working_dir: /var/www/web
    ports:
      - 80:80
    container_name: vue-webserver